# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\".\n\x19\x43lientRegistrationRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"-\n\x1a\x43lientRegistrationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x15GetLatestModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x89\x01\n\x16GetLatestModelResponse\x12\x14\n\x0cround_number\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x12\x12\n\npartner_id\x18\x03 \x01(\t\x12\x13\n\x0bshared_seed\x18\x04 \x01(\x03\x12\x1f\n\x06status\x18\x05 \x01(\x0e\x32\x0f.TrainingStatus\"N\n\x12ModelUpdateRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\"&\n\x13ModelUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"Y\n\x10\x45valuationResult\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x12\x0e\n\x06metric\x18\x04 \x01(\x02*0\n\x0eTrainingStatus\x12\x0f\n\x0bIN_PROGRESS\x10\x00\x12\r\n\tCOMPLETED\x10\x01\x32\xa4\x02\n\x11\x46\x65\x64\x65ratedLearning\x12I\n\x0eRegisterClient\x12\x1a.ClientRegistrationRequest\x1a\x1b.ClientRegistrationResponse\x12\x41\n\x0eGetLatestModel\x12\x16.GetLatestModelRequest\x1a\x17.GetLatestModelResponse\x12>\n\x11SubmitModelUpdate\x12\x13.ModelUpdateRequest\x1a\x14.ModelUpdateResponse\x12\x41\n\x16SubmitEvaluationResult\x12\x11.EvaluationResult\x1a\x14.ModelUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAININGSTATUS']._serialized_start=509
  _globals['_TRAININGSTATUS']._serialized_end=557
  _globals['_CLIENTREGISTRATIONREQUEST']._serialized_start=19
  _globals['_CLIENTREGISTRATIONREQUEST']._serialized_end=65
  _globals['_CLIENTREGISTRATIONRESPONSE']._serialized_start=67
  _globals['_CLIENTREGISTRATIONRESPONSE']._serialized_end=112
  _globals['_GETLATESTMODELREQUEST']._serialized_start=114
  _globals['_GETLATESTMODELREQUEST']._serialized_end=156
  _globals['_GETLATESTMODELRESPONSE']._serialized_start=159
  _globals['_GETLATESTMODELRESPONSE']._serialized_end=296
  _globals['_MODELUPDATEREQUEST']._serialized_start=298
  _globals['_MODELUPDATEREQUEST']._serialized_end=376
  _globals['_MODELUPDATERESPONSE']._serialized_start=378
  _globals['_MODELUPDATERESPONSE']._serialized_end=416
  _globals['_EVALUATIONRESULT']._serialized_start=418
  _globals['_EVALUATIONRESULT']._serialized_end=507
  _globals['_FEDERATEDLEARNING']._serialized_start=560
  _globals['_FEDERATEDLEARNING']._serialized_end=852
# @@protoc_insertion_point(module_scope)
