# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/FederatedLearning/RegisterClient',
                request_serializer=federated__pb2.ClientRegistrationRequest.SerializeToString,
                response_deserializer=federated__pb2.ClientRegistrationResponse.FromString,
                _registered_method=True)
        self.GetLatestModel = channel.unary_unary(
                '/FederatedLearning/GetLatestModel',
                request_serializer=federated__pb2.GetLatestModelRequest.SerializeToString,
                response_deserializer=federated__pb2.GetLatestModelResponse.FromString,
                _registered_method=True)
        self.SubmitModelUpdate = channel.unary_unary(
                '/FederatedLearning/SubmitModelUpdate',
                request_serializer=federated__pb2.ModelUpdateRequest.SerializeToString,
                response_deserializer=federated__pb2.ModelUpdateResponse.FromString,
                _registered_method=True)
        self.SubmitEvaluationResult = channel.unary_unary(
                '/FederatedLearning/SubmitEvaluationResult',
                request_serializer=federated__pb2.EvaluationResult.SerializeToString,
                response_deserializer=federated__pb2.ModelUpdateResponse.FromString,
                _registered_method=True)


class FederatedLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitModelUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitEvaluationResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=federated__pb2.ClientRegistrationRequest.FromString,
                    response_serializer=federated__pb2.ClientRegistrationResponse.SerializeToString,
            ),
            'GetLatestModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestModel,
                    request_deserializer=federated__pb2.GetLatestModelRequest.FromString,
                    response_serializer=federated__pb2.GetLatestModelResponse.SerializeToString,
            ),
            'SubmitModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitModelUpdate,
                    request_deserializer=federated__pb2.ModelUpdateRequest.FromString,
                    response_serializer=federated__pb2.ModelUpdateResponse.SerializeToString,
            ),
            'SubmitEvaluationResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEvaluationResult,
                    request_deserializer=federated__pb2.EvaluationResult.FromString,
                    response_serializer=federated__pb2.ModelUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FederatedLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FederatedLearning/RegisterClient',
            federated__pb2.ClientRegistrationRequest.SerializeToString,
            federated__pb2.ClientRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FederatedLearning/GetLatestModel',
            federated__pb2.GetLatestModelRequest.SerializeToString,
            federated__pb2.GetLatestModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FederatedLearning/SubmitModelUpdate',
            federated__pb2.ModelUpdateRequest.SerializeToString,
            federated__pb2.ModelUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitEvaluationResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FederatedLearning/SubmitEvaluationResult',
            federated__pb2.EvaluationResult.SerializeToString,
            federated__pb2.ModelUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
